// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: src/controllers/arbitragegrpc/proto/arbitrage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArbsOnChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbsOnChainRequest) Reset() {
	*x = ArbsOnChainRequest{}
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbsOnChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbsOnChainRequest) ProtoMessage() {}

func (x *ArbsOnChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbsOnChainRequest.ProtoReflect.Descriptor instead.
func (*ArbsOnChainRequest) Descriptor() ([]byte, []int) {
	return file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescGZIP(), []int{0}
}

func (x *ArbsOnChainRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type OnChainArbitragePathUnit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenInAddress  string                 `protobuf:"bytes,1,opt,name=token_in_address,json=tokenInAddress,proto3" json:"token_in_address,omitempty"`
	TokenOutAddress string                 `protobuf:"bytes,2,opt,name=token_out_address,json=tokenOutAddress,proto3" json:"token_out_address,omitempty"`
	PoolAddress     string                 `protobuf:"bytes,3,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	AmountIn        string                 `protobuf:"bytes,4,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut       string                 `protobuf:"bytes,5,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnChainArbitragePathUnit) Reset() {
	*x = OnChainArbitragePathUnit{}
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainArbitragePathUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainArbitragePathUnit) ProtoMessage() {}

func (x *OnChainArbitragePathUnit) ProtoReflect() protoreflect.Message {
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainArbitragePathUnit.ProtoReflect.Descriptor instead.
func (*OnChainArbitragePathUnit) Descriptor() ([]byte, []int) {
	return file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescGZIP(), []int{1}
}

func (x *OnChainArbitragePathUnit) GetTokenInAddress() string {
	if x != nil {
		return x.TokenInAddress
	}
	return ""
}

func (x *OnChainArbitragePathUnit) GetTokenOutAddress() string {
	if x != nil {
		return x.TokenOutAddress
	}
	return ""
}

func (x *OnChainArbitragePathUnit) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *OnChainArbitragePathUnit) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *OnChainArbitragePathUnit) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

type OnChainArbitrage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Path          []*OnChainArbitragePathUnit `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainArbitrage) Reset() {
	*x = OnChainArbitrage{}
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainArbitrage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainArbitrage) ProtoMessage() {}

func (x *OnChainArbitrage) ProtoReflect() protoreflect.Message {
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainArbitrage.ProtoReflect.Descriptor instead.
func (*OnChainArbitrage) Descriptor() ([]byte, []int) {
	return file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescGZIP(), []int{2}
}

func (x *OnChainArbitrage) GetPath() []*OnChainArbitragePathUnit {
	if x != nil {
		return x.Path
	}
	return nil
}

type ArbsOnChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Arbitrages    []*OnChainArbitrage    `protobuf:"bytes,2,rep,name=arbitrages,proto3" json:"arbitrages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbsOnChainResponse) Reset() {
	*x = ArbsOnChainResponse{}
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbsOnChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbsOnChainResponse) ProtoMessage() {}

func (x *ArbsOnChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbsOnChainResponse.ProtoReflect.Descriptor instead.
func (*ArbsOnChainResponse) Descriptor() ([]byte, []int) {
	return file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescGZIP(), []int{3}
}

func (x *ArbsOnChainResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ArbsOnChainResponse) GetArbitrages() []*OnChainArbitrage {
	if x != nil {
		return x.Arbitrages
	}
	return nil
}

var File_src_controllers_arbitragegrpc_proto_arbitrage_proto protoreflect.FileDescriptor

const file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDesc = "" +
	"\n" +
	"3src/controllers/arbitragegrpc/proto/arbitrage.proto\x12\tarbitrage\"/\n" +
	"\x12ArbsOnChainRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"\xcf\x01\n" +
	"\x18OnChainArbitragePathUnit\x12(\n" +
	"\x10token_in_address\x18\x01 \x01(\tR\x0etokenInAddress\x12*\n" +
	"\x11token_out_address\x18\x02 \x01(\tR\x0ftokenOutAddress\x12!\n" +
	"\fpool_address\x18\x03 \x01(\tR\vpoolAddress\x12\x1b\n" +
	"\tamount_in\x18\x04 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x05 \x01(\tR\tamountOut\"K\n" +
	"\x10OnChainArbitrage\x127\n" +
	"\x04path\x18\x01 \x03(\v2#.arbitrage.OnChainArbitragePathUnitR\x04path\"m\n" +
	"\x13ArbsOnChainResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12;\n" +
	"\n" +
	"arbitrages\x18\x02 \x03(\v2\x1b.arbitrage.OnChainArbitrageR\n" +
	"arbitrages2\\\n" +
	"\tarbitrage\x12O\n" +
	"\x0eGetArbsOnChain\x12\x1d.arbitrage.ArbsOnChainRequest\x1a\x1e.arbitrage.ArbsOnChainResponseBPZNgithub.com/alexkalak/arbandit/services/arbitrageservice/controllers/grpc/protob\x06proto3"

var (
	file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescOnce sync.Once
	file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescData []byte
)

func file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescGZIP() []byte {
	file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescOnce.Do(func() {
		file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDesc), len(file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDesc)))
	})
	return file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDescData
}

var file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_controllers_arbitragegrpc_proto_arbitrage_proto_goTypes = []any{
	(*ArbsOnChainRequest)(nil),       // 0: arbitrage.ArbsOnChainRequest
	(*OnChainArbitragePathUnit)(nil), // 1: arbitrage.OnChainArbitragePathUnit
	(*OnChainArbitrage)(nil),         // 2: arbitrage.OnChainArbitrage
	(*ArbsOnChainResponse)(nil),      // 3: arbitrage.ArbsOnChainResponse
}
var file_src_controllers_arbitragegrpc_proto_arbitrage_proto_depIdxs = []int32{
	1, // 0: arbitrage.OnChainArbitrage.path:type_name -> arbitrage.OnChainArbitragePathUnit
	2, // 1: arbitrage.ArbsOnChainResponse.arbitrages:type_name -> arbitrage.OnChainArbitrage
	0, // 2: arbitrage.arbitrage.GetArbsOnChain:input_type -> arbitrage.ArbsOnChainRequest
	3, // 3: arbitrage.arbitrage.GetArbsOnChain:output_type -> arbitrage.ArbsOnChainResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_controllers_arbitragegrpc_proto_arbitrage_proto_init() }
func file_src_controllers_arbitragegrpc_proto_arbitrage_proto_init() {
	if File_src_controllers_arbitragegrpc_proto_arbitrage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDesc), len(file_src_controllers_arbitragegrpc_proto_arbitrage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_controllers_arbitragegrpc_proto_arbitrage_proto_goTypes,
		DependencyIndexes: file_src_controllers_arbitragegrpc_proto_arbitrage_proto_depIdxs,
		MessageInfos:      file_src_controllers_arbitragegrpc_proto_arbitrage_proto_msgTypes,
	}.Build()
	File_src_controllers_arbitragegrpc_proto_arbitrage_proto = out.File
	file_src_controllers_arbitragegrpc_proto_arbitrage_proto_goTypes = nil
	file_src_controllers_arbitragegrpc_proto_arbitrage_proto_depIdxs = nil
}
