// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: src/controllers/arbitragegrpc/proto/arbitrage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Arbitrage_GetArbsOnChain_FullMethodName = "/arbitrage.arbitrage/GetArbsOnChain"
)

// ArbitrageClient is the client API for Arbitrage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArbitrageClient interface {
	GetArbsOnChain(ctx context.Context, in *ArbsOnChainRequest, opts ...grpc.CallOption) (*ArbsOnChainResponse, error)
}

type arbitrageClient struct {
	cc grpc.ClientConnInterface
}

func NewArbitrageClient(cc grpc.ClientConnInterface) ArbitrageClient {
	return &arbitrageClient{cc}
}

func (c *arbitrageClient) GetArbsOnChain(ctx context.Context, in *ArbsOnChainRequest, opts ...grpc.CallOption) (*ArbsOnChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArbsOnChainResponse)
	err := c.cc.Invoke(ctx, Arbitrage_GetArbsOnChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArbitrageServer is the server API for Arbitrage service.
// All implementations must embed UnimplementedArbitrageServer
// for forward compatibility.
type ArbitrageServer interface {
	GetArbsOnChain(context.Context, *ArbsOnChainRequest) (*ArbsOnChainResponse, error)
	mustEmbedUnimplementedArbitrageServer()
}

// UnimplementedArbitrageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArbitrageServer struct{}

func (UnimplementedArbitrageServer) GetArbsOnChain(context.Context, *ArbsOnChainRequest) (*ArbsOnChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArbsOnChain not implemented")
}
func (UnimplementedArbitrageServer) mustEmbedUnimplementedArbitrageServer() {}
func (UnimplementedArbitrageServer) testEmbeddedByValue()                   {}

// UnsafeArbitrageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArbitrageServer will
// result in compilation errors.
type UnsafeArbitrageServer interface {
	mustEmbedUnimplementedArbitrageServer()
}

func RegisterArbitrageServer(s grpc.ServiceRegistrar, srv ArbitrageServer) {
	// If the following call pancis, it indicates UnimplementedArbitrageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Arbitrage_ServiceDesc, srv)
}

func _Arbitrage_GetArbsOnChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArbsOnChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArbitrageServer).GetArbsOnChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arbitrage_GetArbsOnChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArbitrageServer).GetArbsOnChain(ctx, req.(*ArbsOnChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Arbitrage_ServiceDesc is the grpc.ServiceDesc for Arbitrage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arbitrage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arbitrage.arbitrage",
	HandlerType: (*ArbitrageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArbsOnChain",
			Handler:    _Arbitrage_GetArbsOnChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/controllers/arbitragegrpc/proto/arbitrage.proto",
}
